INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0001', 'ログインできませんでした');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0002', '現在のパスワードが異なります');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0003', 'データを取得できませんでした');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0010', '登録失敗しました');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0011', '更新失敗しました');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('E0012', '削除失敗しました');
INSERT INTO MT_MSG(MESSAGE_ID, MESSAGE) VALUES ('W0001', '検索結果が0件です');
